### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by karwan-ali** [k4ds3/react-activity-rings#1] opened 2023-02-10 23:47 UTC
Hello,

I am wondering if this is possible to implement to React Native also?

I can't get it to work there :/

**Comment by JonasDoesThings** [comment] 2023-02-11 15:48
Hey! @karwan-ali could you please share what errors / problems you encounter when trying to use this component with React Native?

For testing I've just created an expo project and it worked for me. Please share any problems / logs / errors that you encountered

**Comment by karwan-ali** [comment] 2023-02-12 19:59
Hello @JonasDoesThings,

Could you provide me the example that is working for you maybe?

This is my code:
```
const MenuScreen = () => {
  const navigation = useNavigation<CustomerScreenNavigationProd>();

  useLayoutEffect(() => {
    navigation.setOptions({
      headerShown: false,
    });
  }, []);

  return (
    <SafeAreaView style={tw.style('bg-defaultBg w-full h-full')}>
      <ScrollView>
        <ActivityRings
          rings={[
            { filledPercentage: 0.5, color: '#fa0e5a' },
            { filledPercentage: 0.75, color: '#afff02' },
            { filledPercentage: 0.25, color: '#00fff8' },
          ]}
        />
      </ScrollView>
    </SafeAreaView>
  );
};
```


See attached image on what the error is.
<img width="454" alt="Screenshot 2023-02-12 at 20 57 32" src="https://user-images.githubusercontent.com/38838635/218334063-4632d3d2-cb70-436f-a490-630830a9a7bf.png">

**Comment by JonasDoesThings** [comment] 2023-02-18 16:17
Hey, I got around looking into the issue, you're right, it's broken when using react-native on non-web platforms.

The cause is the usage of the web-native <svg> component and it's descendents.

I've quickly tried forking the project and using [react-native-svg](https://github.com/software-mansion/react-native-svg) as a react-native compatible SVG component, but the next roadblock I've encountered was, that this library does not support animations. It seems like you can use [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated/) for these animations.

Sadly I have no expertise in react-native and currently no time for creating a supported fork, so React Native is out of scope at the current point in time :(

I will add a note into the README accordingly

**Comment by JonasDoesThings** [comment] 2023-02-26 19:36
Currently out of scope

**Comment by JonasDoesThings** [comment] 2023-02-26 19:36
Currently out of scope

**Closed as not planned by JonasDoesThings** 2023-02-26 19:36 UTC
